openapi: 3.0.0
info:
  title: Ecomarce
  version: 1.0.0
  description: E-commerce Express Server is a robust and efficient solution designed to streamline and enhance the performance of online retail businesses. This specialized server serves as the backbone of e-commerce operations, ensuring seamless transactions, secure data handling, and optimal user experiences.
  contact:
    name: ABU TAHER
    url: https://github.com/taher267
    email: abutaher267@gmail.com
servers:
  - description: Dev
    url: "http://localhost:4001/api/v1"
tags:
  - name: Auth
    description: Authentication Endpoints (public)
  - name: Product
    description: Product Endpoints (public+private)
  - name: Review
    description: Review Endpoints (Private)
  - name: User
    description: User Endpoints (Private)
paths:
  "/auth/register":
    post:
      description: "Create a new account"
      tags:
        - "Auth"
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Abu Taher
                email:
                  type: string
                  format: email
                  example: example@domain.com
                password:
                  type: string
                  format: password
                  example: password13r
              required:
                - "name"
                - "email"
                - "password"
      responses:
        "201":
          description: Signup successful
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 201
                  message:
                    type: string
                    example: Signup Successful
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
